server:
  port: 9202

spring:

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/time_manager
    username: root
    password: 1001
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 단계에만 사용 (운영에서는 validate 또는 none)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

